# site settings
title: @jstepanovas
subtitle: DESIGNER
email: j.stepanovas@icloud.com
description: Tech-driven designer with a love for open-source customization and visual detail. Exploring the intersection of functionality and aesthetics. ⚙️✨
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: @jstepanovas
street_address: Sea Tower, Corniche
city: Abu Dhabi
state: AD
# zip_code: 55555
country: United Arab Emirates
phone: +971588544264

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/jstepanovas
  #GitLab:
#  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram: https://www.instagram.com/jstepanovas
  LinkedIn: https://www.linkedin.com/in/jstepanovas
  Twitter: https://x.com/jstepanovas
  #Facebook:
  #Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
